// tutorials/angular/solution/stocks/src/app/stock-details/stock-details.component.ts
import { Component, OnInit, OnDestroy } from "@angular/core";
import { DataService } from '../data.service';
import { Stock, GlueStatus } from '../types';
import { GlueService } from '../glue.service';
import { Glue42Web } from "@glue42/web";

@Component({
    templateUrl: './stock-details.component.html'
})
export class StockDetailsComponent implements OnInit, OnDestroy {

    public stock: Stock;
    public glueStatus: GlueStatus = "disconnected";
    public clientMessage: string;
    private glueSubscription: Glue42Web.Interop.Subscription;

    constructor(
        private readonly dataService: DataService,
        private readonly glueService: GlueService
    ) { }

    public async ngOnInit(): Promise<void> {
        this.glueStatus = this.glueService.glueStatus;
        this.stock = this.dataService.selectedStock;

        if (this.glueStatus === "available") {
            this.stock = await this.glueService.getMyContext();
            this.glueSubscription = await this.glueService.subscribeToLivePrices(this.stock);
            this.glueService.subscribeToSharedContext().catch(console.log);
        }

        this.glueService.onClientSelected()
            .subscribe((client) => {
                this.clientMessage = client.portfolio.includes(this.stock.RIC) ?
                    `${client.name} has this stock in the portfolio` :
                    `${client.name} does NOT have this stock in the portfolio`;
            });

        this.glueService.onPriceUpdate().subscribe((newPrices) => {
            this.stock.Ask = newPrices.Ask;
            this.stock.Bid = newPrices.Bid;
        });
    }

    public ngOnDestroy(): void {
        if (this.glueSubscription) {
            this.glueSubscription.close();
        }
    }

}

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <span id="glueSpan" class="label label-warning">Glue42 is {{glueStatus}}</span>
            </div>
            <div class="col-md-10">
                <h1 class="text-center">Stocks</h1>
            </div>
        </div>
        <div *ngIf=clientMessage class="row">
            <div class="col-md-12">
                <h3>{{clientMessage}}</h3>
            </div>
        </div>
        <div class="row">
            <table id="clientsTable" class="table table-hover">
                <tbody>
                    <tr>
                        <th>RIC</th>
                        <td>{{stock?.RIC}}</td>
                    </tr>
                    <tr>
                        <th>BPOD</th>
                        <td>{{stock?.BPOD}}</td>
                    </tr>
                    <tr>
                        <th>Bloomberg</th>
                        <td>{{stock?.Bloomberg}}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{stock?.Description}}</td>
                    </tr>
                    <tr>
                        <th>Exchange</th>
                        <td>{{stock?.Exchange}}</td>
                    </tr>
                    <tr>
                        <th>Venues</th>
                        <td>{{stock?.Venues}}</td>
                    </tr>
                    <tr>
                        <th>Bid</th>
                        <td>{{stock?.Bid}}</td>
                    </tr>
                    <tr>
                        <th>Ask</th>
                        <td>{{stock?.Ask}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>

// tutorials/react/solution/Stocks/src/StockDetails.jsx
import React, { useState, useContext } from 'react';
import { useGlue, GlueContext } from '@glue42/react-hooks';
import {
    subscribeForInstrumentStream,
    getMyWindowContext,
    subscribeForSharedContext,
} from './glue';

function StockDetails() {
    const [{ clientId, clientName, portfolio }, setClient] = useState({});
    const [{ Bid, Ask }, setPrices] = useState({});
    const glue = useContext(GlueContext);
    const windowContext = useGlue(getMyWindowContext);
    const { symbol: { RIC, BPOD, Bloomberg, Description, Exchange, Venues } = {} } =
        windowContext || {};
    useGlue(subscribeForInstrumentStream(setPrices), [RIC]);
    useGlue(subscribeForSharedContext(setClient));

    return (
        <div className="container-fluid">
            <div className="row">
                <div className="col-md-2">
                    {!glue && (
                        <span id="glueSpan" className="badge badge-warning">
                            Glue is unavailable
                        </span>
                    )}
                    {glue && (
                        <span id="glueSpan" className="badge badge-success">
                            Glue is available
                        </span>
                    )}
                </div>
                <div className="col-md-10">
                    <h1 className="text-center">Stock {RIC} Details</h1>
                </div>
            </div>
            <div className="row">
                {clientId && (
                    <>
                        <h2 className="p-3">
                            Client {clientName} - {clientId}{' '}
                        </h2>
                        {RIC && portfolio.length && !portfolio.includes(RIC) && (
                            <h4 className="p-3">
                                Client does not have this instrument in the portfolio
                            </h4>
                        )}
                    </>
                )}
                <div className="col-md-12">
                    <table id="clientsTable" className="table table-hover">
                        <tbody>
                            <tr>
                                <th>RIC</th>
                                <td>{RIC}</td>
                            </tr>
                            <tr>
                                <th>BPOD</th>
                                <td>{BPOD}</td>
                            </tr>
                            <tr>
                                <th>Bloomberg</th>
                                <td>{Bloomberg}</td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td>{Description && Description.toUpperCase()}</td>
                            </tr>
                            <tr>
                                <th>Exchange</th>
                                <td>{Exchange}</td>
                            </tr>
                            <tr>
                                <th>Venues</th>
                                <td>{Venues}</td>
                            </tr>
                            <tr>
                                <th>Bid</th>
                                <td>{Bid}</td>
                            </tr>
                            <tr>
                                <th>Ask</th>
                                <td>{Ask}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}

export default StockDetails;
