// tutorials/react/start/Stocks/src/StockDetails.jsx
import React from 'react';

function StockDetails() {
    const { RIC, BPOD, Bloomberg, Description, Exchange, Venues, Bid, Ask } =
        JSON.parse(sessionStorage.getItem('stock')) || {};

    return (
        <div className="container-fluid">
            <div className="row">
                <div className="col-md-10">
                    <h1 className="text-center">Stock {RIC} Details</h1>
                </div>
            </div>
            <div className="row">
                <table id="clientsTable" className="table table-hover">
                    <tbody>
                        <tr>
                            <th>RIC</th>
                            <td>{RIC}</td>
                        </tr>
                        <tr>
                            <th>BPOD</th>
                            <td>{BPOD}</td>
                        </tr>
                        <tr>
                            <th>Bloomberg</th>
                            <td>{Bloomberg}</td>
                        </tr>
                        <tr>
                            <th>Description</th>
                            <td>{Description}</td>
                        </tr>
                        <tr>
                            <th>Exchange</th>
                            <td>{Exchange}</td>
                        </tr>
                        <tr>
                            <th>Venues</th>
                            <td>{Venues}</td>
                        </tr>
                        <tr>
                            <th>Bid</th>
                            <td>{Bid}</td>
                        </tr>
                        <tr>
                            <th>Ask</th>
                            <td>{Ask}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    );
}

export default StockDetails;

// tutorials/angular/start/stocks/src/app/stock-details/stock-details.component.ts
import { Component, OnInit } from "@angular/core";
import { DataService } from '../data.service';
import { Stock, GlueStatus } from '../types';
import { GlueService } from '../glue.service';

@Component({
    templateUrl: './stock-details.component.html'
})
export class StockDetailsComponent implements OnInit {

    public stock: Stock;
    public glueStatus: GlueStatus = "disconnected";
    public clientMessage: string;
    // private glueSubscription: Glue42Web.Interop.Subscription;

    constructor(private readonly dataService: DataService, private readonly glueService: GlueService) { }

    public ngOnInit(): void {
        this.stock = this.dataService.selectedStock;
    }

}

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <span id="glueSpan" class="label label-warning">Glue is {{glueStatus}}</span>
            </div>
            <div class="col-md-10">
                <h1 class="text-center">Stocks</h1>
            </div>
        </div>
        <div *ngIf=clientMessage class="row">
            <div class="col-md-12">
                <h3>{{clientMessage}}</h3>
            </div>
        </div>
        <div class="row">
            <table id="clientsTable" class="table table-hover">
                <tbody>
                    <tr>
                        <th>RIC</th>
                        <td>{{stock?.RIC}}</td>
                    </tr>
                    <tr>
                        <th>BPOD</th>
                        <td>{{stock?.BPOD}}</td>
                    </tr>
                    <tr>
                        <th>Bloomberg</th>
                        <td>{{stock?.Bloomberg}}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{stock?.Description}}</td>
                    </tr>
                    <tr>
                        <th>Exchange</th>
                        <td>{{stock?.Exchange}}</td>
                    </tr>
                    <tr>
                        <th>Venues</th>
                        <td>{{stock?.Venues}}</td>
                    </tr>
                    <tr>
                        <th>Bid</th>
                        <td>{{stock?.Bid}}</td>
                    </tr>
                    <tr>
                        <th>Ask</th>
                        <td>{{stock?.Ask}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>
